development:
  adapter: postgresql
  database: phoenix-down
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: phoenix-down
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: phoenix-down
  pool: 5
  timeout: 5000